name: Smoke Testing Suite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm run cy:run

      - name: Create Report Directory
        run: mkdir -p cypress/results cypress/reports
      
      - name: Generate Report
        run: npm run generate-report

      - name: Upload Cypress Test Results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/reports
